### PR TITLE
Fix overlapping patterns

### PR DESCRIPTION
**Pull request by semvis123**
Fixes overlapping patterns not working correctly.

### CODE REVIEW

**Comment by zricethezav** [comment]
perfection, thanks @semvis123! 🥳

**Comment by zricethezav** [comment]
Actually @semvis123 doing a little more testing it seems there is still a bug. Check this out:

```
func TestOverlappingPatterns4(t *testing.T) {
	trieBuilder := NewAhoCorasickBuilder(Opts{
		AsciiCaseInsensitive: true,
		MatchOnlyWholeWords:  false,
		MatchKind:            StandardMatch,
		DFA:                  false,
	})

	patterns := []string{"npm_", "npm"}

	trie := trieBuilder.Build(patterns)
	result := trie.FindAll("npm_token=")
	if len(result) != 2 {
		t.Logf("%+v", result)
		t.Error("Did not find match in string")
		t.FailNow()
	}
}
```

Ideally, we should see 2 matches since `npm_token` contains both `npm` and `npm_`

**Comment by semvis123** [comment]
Okay, thanks for the testcase. I will see if I can find something, it probably won't be this week though.
I don't expect this to be an easy fix, because it should continue from the match starting position without matching the same pattern twice.

**Comment by semvis123** [comment]
@zricethezav I tested the `overlappingIter` and it seems to be working fine, I wonder if it was working correctly this whole time. But the functionality wasn't exposed in the findall method.
The testcase passes when the `overlappingIter` is used like this.
```
func TestOverlappingPatterns4(t *testing.T) {
	trieBuilder := NewAhoCorasickBuilder(Opts{
		AsciiCaseInsensitive: true,
		MatchOnlyWholeWords:  false,
		MatchKind:            StandardMatch,
		DFA:                  false,
	})

	patterns := []string{"npm_", "npm"}

	trie := trieBuilder.Build(patterns)
	itr := newOverlappingIter(trie, []byte("npm_token="))
	var result []Match
	for n := itr.Next(); n != nil; n = itr.Next() {
		result = append(result, *n)
	}
	if len(result) != 2 {
		t.Logf("%+v", result)
		t.Error("Did not find match in string")
		t.FailNow()
	}
}
```

**Pull request merged**
